import type { SpellCategory } from "./types"

export const spellCategories: SpellCategory[] = [
  {
    id: "fire",
    name: "Fire",
    color: "red",
    spells: [
      {
        id: "fire1",
        name: "Fire Cat",
        description: "Deals 80 Fire damage",
        pips: 1,
        school: "fire",
        damage: 80,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "fire2",
        name: "Fire Elf",
        description: "Deals 110 Fire damage over time",
        pips: 2,
        school: "fire",
        damage: 0,
        damageOverTime: 110,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "fire3",
        name: "Sunbird",
        description: "Deals 170 Fire damage",
        pips: 3,
        school: "fire",
        damage: 170,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "fire4",
        name: "Phoenix",
        description: "Deals 350 Fire damage",
        pips: 4,
        school: "fire",
        damage: 350,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "fire5",
        name: "Efreet",
        description: "Deals 425 Fire damage and -90% accuracy",
        pips: 7,
        school: "fire",
        damage: 425,
        utility: true,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 90,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
    ],
  },
  {
    id: "ice",
    name: "Ice",
    color: "blue",
    spells: [
      {
        id: "ice1",
        name: "Frost Beetle",
        description: "Deals 65 Ice damage",
        pips: 1,
        school: "ice",
        damage: 65,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "ice2",
        name: "Snow Serpent",
        description: "Deals 105 Ice damage",
        pips: 2,
        school: "ice",
        damage: 105,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "ice3",
        name: "Evil Snowman",
        description: "Deals 160 Ice damage",
        pips: 3,
        school: "ice",
        damage: 160,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "ice4",
        name: "Ice Wyvern",
        description: "Deals 295 Ice damage and -25% accuracy",
        pips: 5,
        school: "ice",
        damage: 295,
        utility: true,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 25,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "ice5",
        name: "Frost Giant",
        description: "Deals 375 Ice damage and stuns",
        pips: 6,
        school: "ice",
        damage: 375,
        utility: true,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 100, // Stun is considered 100% debuff
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
    ],
  },
  {
    id: "storm",
    name: "Storm",
    color: "purple",
    spells: [
      {
        id: "storm1",
        name: "Thunder Snake",
        description: "Deals 90 Storm damage",
        pips: 1,
        school: "storm",
        damage: 90,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "storm2",
        name: "Lightning Bats",
        description: "Deals 125 Storm damage",
        pips: 2,
        school: "storm",
        damage: 125,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "storm3",
        name: "Storm Shark",
        description: "Deals 190 Storm damage",
        pips: 3,
        school: "storm",
        damage: 190,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "storm4",
        name: "Kraken",
        description: "Deals 300 Storm damage",
        pips: 4,
        school: "storm",
        damage: 300,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "storm5",
        name: "Triton",
        description: "Deals 420 Storm damage",
        pips: 5,
        school: "storm",
        damage: 420,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
    ],
  },
  {
    id: "life",
    name: "Life",
    color: "green",
    spells: [
      {
        id: "life1",
        name: "Imp",
        description: "Deals 75 Life damage",
        pips: 1,
        school: "life",
        damage: 75,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "life2",
        name: "Sprite",
        description: "Heals 305 health over time",
        pips: 1,
        school: "life",
        utility: true,
        damage: 0,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 305,
        pipsGained: 0,
      },
      {
        id: "life3",
        name: "Fairy",
        description: "Heals 400 health",
        pips: 2,
        school: "life",
        utility: true,
        damage: 0,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 400,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "life4",
        name: "Nature's Wrath",
        description: "Deals 150 Life damage",
        pips: 3,
        school: "life",
        damage: 150,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "life5",
        name: "Rebirth",
        description: "Heals all allies 500 health",
        pips: 7,
        school: "life",
        utility: true,
        damage: 0,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 500,
        healingOverTime: 0,
        pipsGained: 0,
      },
    ],
  },
  {
    id: "death",
    name: "Death",
    color: "gray",
    spells: [
      {
        id: "death1",
        name: "Dark Sprite",
        description: "Deals 85 Death damage",
        pips: 1,
        school: "death",
        damage: 85,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "death2",
        name: "Ghoul",
        description: "Deals 160 Death damage and heals self for half",
        pips: 3,
        school: "death",
        damage: 160,
        utility: true,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 80,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "death3",
        name: "Vampire",
        description: "Deals 250 Death damage and heals self for half",
        pips: 4,
        school: "death",
        damage: 250,
        utility: true,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 125,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "death4",
        name: "Skeletal Dragon",
        description: "Deals 400 Death damage over time",
        pips: 7,
        school: "death",
        damage: 0,
        damageOverTime: 400,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "death5",
        name: "Scarecrow",
        description: "Deals 300 Death damage to all enemies",
        pips: 7,
        school: "death",
        damage: 300,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
    ],
  },
  {
    id: "myth",
    name: "Myth",
    color: "yellow",
    spells: [
      {
        id: "myth1",
        name: "Blood Bat",
        description: "Deals 80 Myth damage",
        pips: 1,
        school: "myth",
        damage: 80,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "myth2",
        name: "Troll",
        description: "Deals 120 Myth damage",
        pips: 2,
        school: "myth",
        damage: 120,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "myth3",
        name: "Cyclops",
        description: "Deals 180 Myth damage",
        pips: 3,
        school: "myth",
        damage: 180,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "myth4",
        name: "Minotaur",
        description: "Deals 300 Myth damage",
        pips: 4,
        school: "myth",
        damage: 300,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "myth5",
        name: "Orthrus",
        description: "Deals 380 Myth damage",
        pips: 6,
        school: "myth",
        damage: 380,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
    ],
  },
  {
    id: "balance",
    name: "Balance",
    color: "orange",
    spells: [
      {
        id: "balance1",
        name: "Scarab",
        description: "Deals 70 Balance damage",
        pips: 1,
        school: "balance",
        damage: 70,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "balance2",
        name: "Scorpion",
        description: "Deals 110 Balance damage",
        pips: 2,
        school: "balance",
        damage: 110,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "balance3",
        name: "Locust Swarm",
        description: "Deals 170 Balance damage",
        pips: 3,
        school: "balance",
        damage: 170,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "balance4",
        name: "Judgment",
        description: "Deals damage based on pips",
        pips: 4,
        school: "balance",
        damage: 200,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "balance5",
        name: "Hydra",
        description: "Deals 255 Fire, Ice, and Storm damage",
        pips: 6,
        school: "balance",
        damage: 765,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
    ],
  },
  {
    id: "astral",
    name: "Astral",
    color: "purple",
    spells: [
      {
        id: "astral1",
        name: "Tower Shield",
        description: "Reduces damage by 50%",
        pips: 1,
        school: "astral",
        utility: true,
        damage: 0,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 50,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "astral2",
        name: "Feint",
        description: "Target takes 70% more damage",
        pips: 1,
        school: "astral",
        utility: true,
        damage: 0,
        damageOverTime: 0,
        buffPercentage: 70,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "astral3",
        name: "Hex",
        description: "Target takes 30% more damage",
        pips: 1,
        school: "astral",
        utility: true,
        damage: 0,
        damageOverTime: 0,
        buffPercentage: 30,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "astral4",
        name: "Weakness",
        description: "Target deals 25% less damage",
        pips: 1,
        school: "astral",
        utility: true,
        damage: 0,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 25,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "astral5",
        name: "Reshuffle",
        description: "Reshuffles all discarded cards",
        pips: 3,
        school: "astral",
        utility: true,
        damage: 0,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 3,
      },
    ],
  },
  {
    id: "shadow",
    name: "Shadow",
    color: "black",
    spells: [
      {
        id: "shadow1",
        name: "Dark Nova",
        description: "Deals 350 Shadow damage to all enemies",
        pips: 4,
        school: "shadow",
        damage: 350,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "shadow2",
        name: "Shadow Shrike",
        description: "Gain 30% pierce for 3 rounds",
        pips: 2,
        school: "shadow",
        utility: true,
        damage: 0,
        damageOverTime: 0,
        buffPercentage: 30,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "shadow3",
        name: "Shadow Sentinel",
        description: "Gain 40% universal resist for 3 rounds",
        pips: 2,
        school: "shadow",
        utility: true,
        damage: 0,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 40,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "shadow4",
        name: "Abominable Weaver",
        description: "Deals 595 Ice damage and stuns",
        pips: 5,
        school: "shadow",
        damage: 595,
        utility: true,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 100,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
      {
        id: "shadow5",
        name: "Glowbug Squall",
        description: "Deals 650 Storm damage to all enemies",
        pips: 5,
        school: "shadow",
        damage: 650,
        damageOverTime: 0,
        buffPercentage: 0,
        debuffPercentage: 0,
        healing: 0,
        healingOverTime: 0,
        pipsGained: 0,
      },
    ],
  },
]
